server:
  port: 8080
spring:
  jwt:
    secret: kjvMLWXxW4VDgWK6Cf5QjFiDoCRrQfKDFZQQgmT8gzF2pwfQPy
  data:
    mongodb:
      uri: mongodb+srv://parkjihyeon:hobit1234@mycluster0.ivmxxay.mongodb.net/hobit?retryWrites=true&w=majority&appName=myCluster0
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 377262399790-22fej88tjrehtu9krk5q0aa8bv6e5lp6.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile, email
